# Theoretical Questions:

### 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations ?

### Purpose of NumPy:

NumPy (Numerical Python) is a library designed for efficient numerical computation in scientific computing and data analysis. Its primary purpose is to provide support for:

1. Multi-dimensional arrays and matrices
2. Vectorized operations for fast computations
3. Linear algebra operations
4. Random number generation

### Advantages of NumPy:

1. Speed: NumPy operations are significantly faster than Python's built-in data structures.
2. Memory Efficiency: NumPy arrays require less memory than Python lists.
3. Convenience: NumPy provides a simple and intuitive interface for numerical computations.
4. Interoperability: NumPy arrays can be easily converted to/from Python lists, dictionaries, and Pandas DataFrames.
5. Vectorized Operations: Element-wise operations applicable to entire arrays.

### Enhancing Python's Capabilities:

1. Efficient Numerical Computations: NumPy replaces Python's built-in lists with more efficient arrays.
2. Matrix Operations: NumPy provides optimized linear algebra functions.
3. Random Number Generation: NumPy offers high-quality random number generators.
4. Data Type Support: NumPy supports various data types (integers, floats, complex numbers).
5. Integration with Other Libraries: NumPy is the foundation for many scientific computing libraries in Python (Pandas, SciPy, Matplotlib).

### Key Features:

1. ndarray: Multi-dimensional array data structure.
2. Universal Functions (ufuncs): Element-wise operations.
3. Linear Algebra Functions: Matrix operations, decomposition, and solving systems of equations.
4. Random Number Generation: Functions for generating random numbers.
5. Data Type Support: Various data types supported.

### Applications:

1. Scientific Computing (simulations, optimization)
2. Data Analysis (data cleaning, filtering, transformation)
3. Machine Learning (neural networks, deep learning)
4. Signal Processing (filtering, convolution)
5. Data Science (data visualization, statistical analysis)


In [9]:
import numpy as np

# Create a sample array
arr = np.array([1, 2, 3, 4, 5])

# Basic array operations
print(np.sum(arr))  # Sum of array elements
print(np.mean(arr))  # Mean of array elements
print(np.sqrt(arr))  # Element-wise square root

# Matrix multiplication
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print(np.matmul(mat1, mat2))  # Matrix product


15
3.0
[1.         1.41421356 1.73205081 2.         2.23606798]
[[19 22]
 [43 50]]


#### By leveraging NumPy's capabilities, researchers and developers can efficiently process and analyze complex numerical data, driving advancements in various scientific fields.

## 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other ?

### Similarities

1. Calculate the central tendency of an array.
2. Accept multidimensional arrays as input.
3. Return a scalar value.


Differences

1. Weighted Average

    - np.average(): Allows weighted averages.
    - np.mean(): Does not support weighted averages.

2. Axis Specification

    - np.average(): Specifies axis using the axis parameter.
    - np.mean(): Specifies axis using the axis parameter.

3. Handling of NaNs and Infs

    - np.mean(): Ignores NaNs and Infs by default.
    - np.average(): Ignores NaNs and Infs by default, but can propagate NaNs.

4. Default Behavior for Empty Arrays

    - np.mean(): Returns NaN for empty arrays.
    - np.average(): Returns 0.0 for empty arrays.
  
Comparison Table

| Function | Weighted Average | Axis Specification | NaN/Inf Handling | Empty Array Behavior |
| --- | --- | --- | --- | --- |
| np.mean() | No | Yes (axis arg) | Ignore | NaN |
| np.average() | Yes (weights arg) | Yes (axis arg) | Ignore (or propagate) | 0.0 |


Use Cases

1. Use np.mean():
    - Simple arithmetic mean calculations.
    - Ignoring NaNs and Infs is desired.
    - Working with empty arrays, wanting NaN as the result.

2. Use np.average():
    - Weighted average calculations.
    - Specifying axis along which to compute average.
    - More control over NaN/Inf handling.

Specific scenarios:

1. Data analysis: Use np.mean() for simple mean calculations.
2. Signal processing: Use np.average() for weighted averages.
3. Machine learning: Use np.mean() for model evaluation metrics.
4. Scientific computing: Use np.average() for complex numerical computations.


Best practice:

1. Use np.mean() as the default choice.
2. Switch to np.average() when weighted averages or advanced features are needed.
.

### 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

### Reversing NumPy Arrays

NumPy provides several methods to reverse arrays along different axes:


1. *Using np.flip()*

np.flip() reverses the elements of an array along the specified axis.

Syntax: np.flip(arr, axis=None)

- arr: Input array
- axis: Axis to reverse (None for all axes)

2. *Using np.flipud()*

np.flipud() reverses the elements of an array along the 0th axis (up-down).

Syntax: np.flipud(arr)

3. *Using np.fliplr()*

np.fliplr() reverses the elements of an array along the 1st axis (left-right).

Syntax: np.fliplr(arr)

4. *Using slicing ([::-1])*

Slicing with [::-1] reverses the elements of an array.

Syntax: arr[::-1] (for 1D) or arr[:, ::-1] (for 2D)



In [30]:
### 1D Array


import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse using np.flip()
reversed_arr_1d = np.flip(arr_1d)
print(reversed_arr_1d)  # Output: [5 4 3 2 1]

# Reverse using slicing
reversed_arr_1d_slice = arr_1d[::-1]
print(reversed_arr_1d_slice)  # Output: [5 4 3 2 1]


### 2D Array


# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Reverse rows (axis=0) using np.flip()
reversed_rows = np.flip(arr_2d, axis=0)
print(reversed_rows)
# Output:
# [[4 5 6]
#  [1 2 3]]

# Reverse columns (axis=1) using np.flip()
reversed_cols = np.flip(arr_2d, axis=1)
print(reversed_cols)
# Output:
# [[3 2 1]
#  [6 5 4]]

# Reverse rows using np.flipud()
reversed_rows_ud = np.flipud(arr_2d)
print(reversed_rows_ud)
# Output:
# [[4 5 6]
#  [1 2 3]]

# Reverse columns using np.fliplr()
reversed_cols_lr = np.fliplr(arr_2d)
print(reversed_cols_lr)
# Output:
# [[3 2 1]
#  [6 5 4]]

# Reverse rows using slicing
reversed_rows_slice = arr_2d[::-1, :]
print(reversed_rows_slice)
# Output:
# [[4 5 6]
#  [1 2 3]]

# Reverse columns using slicing
reversed_cols_slice = arr_2d[:, ::-1]
print(reversed_cols_slice)
# Output:
# [[3 2 1]
#  [6 5 4]]



[5 4 3 2 1]
[5 4 3 2 1]
[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]


### 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

### Determining Data Type in NumPy Array

To determine the data type of elements in a NumPy array, use:


1. arr.dtype
2. arr.dtype.name
3. np.dtype(arr)
4. arr.astype

Example


import numpy as np

### Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

### Determine data type
print(arr.dtype)  # Output: int32
print(arr.dtype.name)  # Output: int32
print(np.dtype(arr))  # Output: int32


#### Importance of Data Types

#### Data types play a crucial role in:


1. Memory Management: Efficient memory allocation and deallocation.
2. Performance: Optimized computations and reduced type conversions.
3. Accuracy: Prevents data loss or corruption due to incorrect type casting.


#### NumPy Data Types

1. Integer types (e.g., int8, int16, int32, int64)
2. Floating-point types (e.g., float32, float64)
3. Complex types (e.g., complex64, complex128)
4. Boolean type (bool)
5. Object type (object)
6. String type (str)


#### Benefits of Data Types

1. Memory Efficiency: Reduced memory usage.
2. Faster Computations: Optimized operations.
3. Improved Accuracy: Reduced errors.
4. Better Code Readability: Clear data type intentions.


#### Best Practices

1. Specify data type during array creation.
2. Use np.dtype to verify data type.
3. Avoid implicit type conversions.
4. Optimize data type for specific operations.



### 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

### NumPy ndarrays

In NumPy, an ndarray (N-dimensional array) is a multi-dimensional array object that stores homogeneous data (i.e., same data type). ndarrays are the core data structure in NumPy.


### Key Features:

1. Multi-dimensionality: ndarrays can have any number of dimensions.
2. Homogeneous data: All elements must have the same data type.
3. Vectorized operations: Fast element-wise operations.
4. Memory efficiency: Stores data in contiguous blocks.
5. Flexible indexing: Supports slicing, indexing, and broadcasting.

 
### Comparison with Standard Python Lists:

|  | NumPy ndarrays | Python Lists |
| --- | --- | --- |
| Data Type | Homogeneous | Heterogeneous |
| Memory | Contiguous block | Dynamic allocation |
| Performance | Optimized for numerical computations | General-purpose |
| Indexing | Flexible slicing and indexing | Limited indexing |
| Operations | Vectorized operations | Iterative operations 


### 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

### Performance Benefits of NumPy Arrays

NumPy arrays offer significant performance advantages over Python lists for large-scale numerical operations due to:


1. Vectorized Operations: NumPy performs operations on entire arrays at once, reducing iteration overhead.
2. Compiled C Code: NumPy's core functions are written in C, providing a performance boost.
3. Memory Efficiency: NumPy arrays store data contiguously, minimizing memory access overhead.
4. Cache Locality: NumPy arrays optimize cache usage, reducing memory access times.


### Comparison of NumPy Arrays and Python Lists


| Operation | NumPy Array | Python List |
| --- | --- | --- |
| Element-wise addition | O(n) | O(n^2) |
| Matrix multiplication | O(n^3) | O(n^4) |
| Sorting | O(n log n) | O(n^2) |
| Indexing | O(1) | O(n) |



### 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

### Comparing vstack() and hstack() Functions in NumPy

NumPy provides two functions to stack arrays:


1. np.vstack(): Vertical stacking (row-wise)
2. np.hstack(): Horizontal stacking (column-wise)


Similarities

1. Both functions stack arrays.
2. Both accept multiple arrays as input.


Differences

1. Axis: vstack() stacks along axis=0 (rows), while hstack() stacks along axis=1 (columns).
2. Output Shape: vstack() increases row count, while hstack() increases column count.


In [48]:
# Example :
import numpy as np

# Create arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vertical stacking (vstack)
result_vstack = np.vstack((arr1, arr2))
print(result_vstack)


[[1 2 3]
 [4 5 6]]


In [50]:
# Horizontal stacking (hstack)
result_hstack = np.hstack((arr1, arr2))
print(result_hstack)


[1 2 3 4 5 6]


In [52]:
# Create 2D arrays
arr1_2d = np.array([[1, 2], [3, 4]])
arr2_2d = np.array([[5, 6], [7, 8]])

# Vertical stacking (vstack)
result_vstack_2d = np.vstack((arr1_2d, arr2_2d))
print(result_vstack_2d)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Real-World Applications


1. Data concatenation
2. Image processing
3. Machine learning
4. Scientific computing


### Best Practices


1. Use vstack() for row-wise concatenation.
2. Use hstack() for column-wise concatenation.
3. Ensure input arrays have compatible shapes.
4. Use np.concatenate() for more flexibility.

### 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

### NumPy provides two methods to flip arrays: fliplr() and flipud(). Understanding their differences is crucial for effective array manipulation.


### Differences

| Method | Flip Direction | Axis |
| --- | --- | --- |
| fliplr() | Horizontal (Left-Right) | Axis=1 |
| flipud() | Vertical (Up-Down) | Axis=0 |


### Effects on Array Dimensions


1D Arrays

- fliplr(): Reverses the array (same as flipud()).
- flipud(): Reverses the array.


2D Arrays

- fliplr(): Flips columns (horizontal flip).
- flipud(): Flips rows (vertical flip).


3D Arrays

- fliplr(): Flips along the second axis (horizontal flip).
- flipud(): Flips along the first axis (vertical flip).


N-Dimensional Arrays

- fliplr(): Flips along the specified axis (default: axis=1).
- flipud(): Flips along the specified axis (default: axis=0).



In [63]:
# import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("Original:", arr_1d)
print("fliplr():", np.fliplr([arr_1d]))
print("flipud():", np.flipud([arr_1d]))

Original: [1 2 3 4 5]
fliplr(): [[5 4 3 2 1]]
flipud(): [[1 2 3 4 5]]


In [65]:
# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOriginal:\n", arr_2d)
print("fliplr():\n", np.fliplr(arr_2d))
print("flipud():\n", np.flipud(arr_2d))



Original:
 [[1 2 3]
 [4 5 6]]
fliplr():
 [[3 2 1]
 [6 5 4]]
flipud():
 [[4 5 6]
 [1 2 3]]


In [67]:
# 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nOriginal:\n", arr_3d)
print("fliplr():\n", np.fliplr(arr_3d))
print("flipud():\n", np.flipud(arr_3d))



Original:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
fliplr():
 [[[3 4]
  [1 2]]

 [[7 8]
  [5 6]]]
flipud():
 [[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]


### 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

### Array Split Functionality in NumPy

The array_split() method in NumPy divides an array into multiple sub-arrays along a specified axis.


Syntax


numpy.array_split(ary, indices_or_sections, axis=0)


- ary: Input array
- indices_or_sections: Number of splits or indices to split at
- axis: Axis to split along (default: 0)


### Functionality

1. Equal Splits: If indices_or_sections is an integer, the array is divided into equal-sized sub-arrays.
2. Uneven Splits: If indices_or_sections is a list of indices, the array is split at those specific points.


### Handling Uneven Splits

When the array cannot be divided evenly, array_split() adjusts the size of the last sub-array.



In [75]:
#Examples :-


#import numpy as np

# Create an array
arr = np.arange(10)

# Split into 3 equal parts
split_arr = np.array_split(arr, 3)
print(split_arr)  # [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]

# Split at specific indices
split_arr = np.array_split(arr, [3, 7])
print(split_arr)  # [array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]


[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]


### 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

### Vectorization and Broadcasting in NumPy

Vectorization and broadcasting are fundamental concepts in NumPy that enable efficient array operations.


### Vectorization

Vectorization refers to performing operations on entire arrays at once, rather than iterating over individual elements.


Benefits

1. Faster execution
2. Reduced memory allocation
3. Improved code readability


### Broadcasting

Broadcasting allows NumPy to perform operations on arrays with different shapes and sizes.


Rules

1. If shapes are equal, perform element-wise operation.
2. If one array has a singleton dimension (size 1), broadcast it.
3. If shapes are incompatible, raise an error.

### Contribution to Efficient Array Operations

Vectorization and broadcasting enable:


1. Faster execution: Reduced iteration overhead.
2. Memory efficiency: Minimized memory allocation.
3. Flexible operations: Support for various array shapes.
4. Simplified code: Reduced need for loops.




# Practical Questions:

### 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [85]:
#import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(arr)

# Interchange rows and columns using transpose()
arr_transposed = arr.transpose()
print("\nTransposed Array:")
print(arr_transposed)

# Alternatively, use np.transpose() or arr.T
arr_transposed_alt1 = np.transpose(arr)
arr_transposed_alt2 = arr.T
print("\nAlternative Transposed Array (np.transpose()):")
print(arr_transposed_alt1)
print("\nAlternative Transposed Array (arr.T):")
print(arr_transposed_alt2)


Original Array:
[[72 31 29]
 [24  4 84]
 [45 44 55]]

Transposed Array:
[[72 24 45]
 [31  4 44]
 [29 84 55]]

Alternative Transposed Array (np.transpose()):
[[72 24 45]
 [31  4 44]
 [29 84 55]]

Alternative Transposed Array (arr.T):
[[72 24 45]
 [31  4 44]
 [29 84 55]]


### 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [88]:

#import numpy as np

# Generate a 1D NumPy array with 10 elements
arr_1d = np.arange(1, 11)
print("Original 1D Array:")
print(arr_1d)

# Reshape into a 2x5 array
arr_2x5 = arr_1d.reshape(2, 5)
print("\nReshaped 2x5 Array:")
print(arr_2x5)

# Reshape into a 5x2 array
arr_5x2 = arr_1d.reshape(5, 2)
print("\nReshaped 5x2 Array:")
print(arr_5x2)


Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


### 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [92]:
#import numpy as np

# Create a 4x4 NumPy array with random float values
arr = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(arr)

# Add a border of zeros around the array
arr_bordered = np.pad(arr, ((1, 1), (1, 1)), mode='constant')
print("\nBordered 6x6 Array:")
print(arr_bordered)


Original 4x4 Array:
[[0.16309992 0.8650382  0.58485089 0.14905726]
 [0.35788477 0.36035181 0.31466056 0.46144058]
 [0.00612222 0.88779018 0.20540065 0.01141513]
 [0.79329431 0.07759107 0.12859046 0.50282443]]

Bordered 6x6 Array:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.16309992 0.8650382  0.58485089 0.14905726 0.        ]
 [0.         0.35788477 0.36035181 0.31466056 0.46144058 0.        ]
 [0.         0.00612222 0.88779018 0.20540065 0.01141513 0.        ]
 [0.         0.79329431 0.07759107 0.12859046 0.50282443 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


### 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [94]:
# import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
arr = np.arange(10, 61, 5)
print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


### 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [97]:
### import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(arr)
lowercase = np.char.lower(arr)
title_case = np.char.title(arr)
uppercase_first_letter = np.char.capitalize(arr)
swapcase = np.char.swapcase(arr)

# Print the results
print("Original Array:")
print(arr)
print("\nUppercase:")
print(uppercase)
print("\nLowercase:")
print(lowercase)
print("\nTitle Case:")
print(title_case)
print("\nUppercase First Letter:")
print(uppercase_first_letter)
print("\nSwapcase:")
print(swapcase)



Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Uppercase First Letter:
['Python' 'Numpy' 'Pandas']

Swapcase:
['PYTHON' 'NUMPY' 'PANDAS']


### 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [103]:
import numpy as np

# Generate a NumPy array of words
words = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_words = [' '.join(list(word)) for word in words]

print("Original Array:")
print(words)
print("\nSpaced Array:")
print(spaced_words)



Original Array:
['hello' 'world' 'numpy' 'python']

Spaced Array:
['h e l l o', 'w o r l d', 'n u m p y', 'p y t h o n']


### 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [109]:
# import numpy as np

# Create two 2D NumPy arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)

# Perform element-wise operations
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("\nElement-wise Addition:")
print(addition)
print("\nElement-wise Subtraction:")
print(subtraction)
print("\nElement-wise Multiplication:")
print(multiplication)
print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


### 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [112]:
# import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


### 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [116]:
# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, 100)
print("Random Array:")
print(random_array)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]
print("\nPrime Numbers:")
print(prime_numbers)


Random Array:
[769 278 169 620 235 462  23 862 756 358 384 846 836 242 789  90 652 365
 254 275 727 963 104 904 323 891 657 794 416 440 567 527 309 534   1  68
  66 543 428 105 831 170 728 892 169 251 370 589 717 256 298 268 994 356
 957 831  67 767 765 464 342 455 794 169 598 633  89  27 434 930 447  25
 811 252 558 949  15  70  30 574 177 584 281  58 410   1 691  73 219 339
 503  12 308 821 359 139 250 967 560 639]

Prime Numbers:
[769, 23, 727, 251, 67, 89, 811, 281, 691, 73, 503, 821, 359, 139, 967]


### 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [121]:
import numpy as np
import calendar

# Create a NumPy array representing daily temperatures for a month (e.g., January)
days_in_month = calendar.monthrange(2024, 1)[1]  # 31 days in January 2024
daily_temperatures = np.random.uniform(20, 40, size=days_in_month)  # Random temperatures between 20°F and 40°F

print("Daily Temperatures (°F):")
print(daily_temperatures)

# Calculate weekly averages
num_weeks = int(np.ceil(days_in_month / 7))  # Calculate number of weeks
weekly_averages = [np.mean(daily_temperatures[i*7:(i+1)*7]) for i in range(num_weeks)]

print("\nWeekly Averages (°F):")
for i, avg in enumerate(weekly_averages):
    print(f"Week {i+1}: {avg:.2f}")



Daily Temperatures (°F):
[36.31669669 30.53345559 26.42852611 27.86581692 29.31716731 31.79323613
 30.91259209 38.48033142 39.25452773 27.39849727 20.00929867 30.71040456
 21.00909814 31.95170859 23.39588926 30.96826221 37.02200442 21.94430505
 21.75263568 21.97669697 34.09191143 28.39834662 30.13389873 35.33167307
 30.71114927 34.30072064 39.68887472 21.33346457 25.21666671 24.05194596
 23.3262312 ]

Weekly Averages (°F):
Week 1: 30.45
Week 2: 29.83
Week 3: 27.31
Week 4: 31.41
Week 5: 24.20
